version: "3.7"
services:
  #mysql
  mysql:
    image:  mysql:latest
    volumes:
      - ./data/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=LookLook
      - MYSQL_ROOT_PASSWORD=123456

  #Redis
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/data/redis:/data
      - ./data/logs/redis:/logs
    command: redis-server --requirepass 123456

  #Consul
  consul:
    image: consul:latest
    command:   agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    volumes:
      - ./consul/data:/consul/data
    ports:
      - "8500:8500"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8600:8600/udp"

  #RabbitMQ
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  #Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib-dev:latest
    command: [ "--config=/etc/otel-collector-config.yaml","${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
        - "1888:1888"   # pprof extension
        - "8888"   # Prometheus' metrics exposed by the collector
        - "8889:8889"   # Prometheus exporter metrics
        - "13133:13133" # health_check extension
        - "4317:4317"   # OTLP gRPC receiver
        - "55679" # zpages extension
    depends_on:
      -  jaeger-all-in-one

  #Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLETCTOR_OTLP_ENABLED=true
    ports:
        - "16686:16686"
        - "14268"
        - "14250:14250"
        - "6831:6831"


  # VictoriaMetrics
  victoriametrics:
      container_name: victoriametrics
      image: victoriametrics/victoria-metrics
      ports:
        - "8428:8428"
        - "8089:8089"
        - "8089:8089/udp"
        - "2003:2003"
        - "2003:2003/udp"
        - "4242:4242"
      command:
        - '--storageDataPath=/storage'
        - '--graphiteListenAddr=:2003'
        - '--opentsdbListenAddr=:4242'
        - '--httpListenAddr=:8428'
        - '--influxListenAddr=:8089'
      restart: always

  # Grafana
  grafana:
      image: grafana/grafana:latest
      ports:
        - "3000:3000"