// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: idl/quic/tank.proto

package quic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TankRemove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TankRemove) Reset() {
	*x = TankRemove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_quic_tank_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TankRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TankRemove) ProtoMessage() {}

func (x *TankRemove) ProtoReflect() protoreflect.Message {
	mi := &file_idl_quic_tank_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TankRemove.ProtoReflect.Descriptor instead.
func (*TankRemove) Descriptor() ([]byte, []int) {
	return file_idl_quic_tank_proto_rawDescGZIP(), []int{0}
}

func (x *TankRemove) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Tank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X         int32 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y         int32 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Direction int32 `protobuf:"varint,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Kill      int32 `protobuf:"varint,5,opt,name=kill,proto3" json:"kill,omitempty"`
}

func (x *Tank) Reset() {
	*x = Tank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_quic_tank_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tank) ProtoMessage() {}

func (x *Tank) ProtoReflect() protoreflect.Message {
	mi := &file_idl_quic_tank_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tank.ProtoReflect.Descriptor instead.
func (*Tank) Descriptor() ([]byte, []int) {
	return file_idl_quic_tank_proto_rawDescGZIP(), []int{1}
}

func (x *Tank) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tank) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Tank) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Tank) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

func (x *Tank) GetKill() int32 {
	if x != nil {
		return x.Kill
	}
	return 0
}

type GetTankList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tank []*Tank `protobuf:"bytes,1,rep,name=tank,proto3" json:"tank,omitempty"`
}

func (x *GetTankList) Reset() {
	*x = GetTankList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_quic_tank_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTankList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTankList) ProtoMessage() {}

func (x *GetTankList) ProtoReflect() protoreflect.Message {
	mi := &file_idl_quic_tank_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTankList.ProtoReflect.Descriptor instead.
func (*GetTankList) Descriptor() ([]byte, []int) {
	return file_idl_quic_tank_proto_rawDescGZIP(), []int{2}
}

func (x *GetTankList) GetTank() []*Tank {
	if x != nil {
		return x.Tank
	}
	return nil
}

type TankMove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Direction int32 `protobuf:"varint,2,opt,name=direction,proto3" json:"direction,omitempty"`
}

func (x *TankMove) Reset() {
	*x = TankMove{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_quic_tank_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TankMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TankMove) ProtoMessage() {}

func (x *TankMove) ProtoReflect() protoreflect.Message {
	mi := &file_idl_quic_tank_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TankMove.ProtoReflect.Descriptor instead.
func (*TankMove) Descriptor() ([]byte, []int) {
	return file_idl_quic_tank_proto_rawDescGZIP(), []int{3}
}

func (x *TankMove) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TankMove) GetDirection() int32 {
	if x != nil {
		return x.Direction
	}
	return 0
}

var File_idl_quic_tank_proto protoreflect.FileDescriptor

var file_idl_quic_tank_proto_rawDesc = []byte{
	0x0a, 0x13, 0x69, 0x64, 0x6c, 0x2f, 0x71, 0x75, 0x69, 0x63, 0x2f, 0x74, 0x61, 0x6e, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x1c, 0x0a, 0x0a, 0x54,
	0x61, 0x6e, 0x6b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x64, 0x0a, 0x04, 0x54, 0x61, 0x6e,
	0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12,
	0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x1c, 0x0a,
	0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6b, 0x69, 0x6c, 0x6c, 0x22,
	0x2d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x61, 0x6e, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x04, 0x74, 0x61, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x54, 0x61, 0x6e, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x6e, 0x6b, 0x22, 0x38,
	0x0a, 0x08, 0x54, 0x61, 0x6e, 0x6b, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x71, 0x75, 0x69,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_quic_tank_proto_rawDescOnce sync.Once
	file_idl_quic_tank_proto_rawDescData = file_idl_quic_tank_proto_rawDesc
)

func file_idl_quic_tank_proto_rawDescGZIP() []byte {
	file_idl_quic_tank_proto_rawDescOnce.Do(func() {
		file_idl_quic_tank_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_quic_tank_proto_rawDescData)
	})
	return file_idl_quic_tank_proto_rawDescData
}

var file_idl_quic_tank_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_idl_quic_tank_proto_goTypes = []interface{}{
	(*TankRemove)(nil),  // 0: game.TankRemove
	(*Tank)(nil),        // 1: game.Tank
	(*GetTankList)(nil), // 2: game.GetTankList
	(*TankMove)(nil),    // 3: game.TankMove
}
var file_idl_quic_tank_proto_depIdxs = []int32{
	1, // 0: game.GetTankList.tank:type_name -> game.Tank
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_idl_quic_tank_proto_init() }
func file_idl_quic_tank_proto_init() {
	if File_idl_quic_tank_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_quic_tank_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TankRemove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_quic_tank_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_quic_tank_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTankList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_quic_tank_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TankMove); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_quic_tank_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idl_quic_tank_proto_goTypes,
		DependencyIndexes: file_idl_quic_tank_proto_depIdxs,
		MessageInfos:      file_idl_quic_tank_proto_msgTypes,
	}.Build()
	File_idl_quic_tank_proto = out.File
	file_idl_quic_tank_proto_rawDesc = nil
	file_idl_quic_tank_proto_goTypes = nil
	file_idl_quic_tank_proto_depIdxs = nil
}
