// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: idl/quic/world.proto

package quic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X      int32 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y      int32 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Width  int32 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height int32 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *Rock) Reset() {
	*x = Rock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_quic_world_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rock) ProtoMessage() {}

func (x *Rock) ProtoReflect() protoreflect.Message {
	mi := &file_idl_quic_world_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rock.ProtoReflect.Descriptor instead.
func (*Rock) Descriptor() ([]byte, []int) {
	return file_idl_quic_world_proto_rawDescGZIP(), []int{0}
}

func (x *Rock) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Rock) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Rock) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Rock) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetRockList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rock []*Rock `protobuf:"bytes,1,rep,name=rock,proto3" json:"rock,omitempty"`
}

func (x *GetRockList) Reset() {
	*x = GetRockList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_quic_world_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRockList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRockList) ProtoMessage() {}

func (x *GetRockList) ProtoReflect() protoreflect.Message {
	mi := &file_idl_quic_world_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRockList.ProtoReflect.Descriptor instead.
func (*GetRockList) Descriptor() ([]byte, []int) {
	return file_idl_quic_world_proto_rawDescGZIP(), []int{1}
}

func (x *GetRockList) GetRock() []*Rock {
	if x != nil {
		return x.Rock
	}
	return nil
}

type NewExplosion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *NewExplosion) Reset() {
	*x = NewExplosion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_quic_world_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewExplosion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewExplosion) ProtoMessage() {}

func (x *NewExplosion) ProtoReflect() protoreflect.Message {
	mi := &file_idl_quic_world_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewExplosion.ProtoReflect.Descriptor instead.
func (*NewExplosion) Descriptor() ([]byte, []int) {
	return file_idl_quic_world_proto_rawDescGZIP(), []int{2}
}

func (x *NewExplosion) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NewExplosion) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type NewExplosionList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExplosionBorn []*NewExplosion `protobuf:"bytes,1,rep,name=explosionBorn,proto3" json:"explosionBorn,omitempty"`
}

func (x *NewExplosionList) Reset() {
	*x = NewExplosionList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_quic_world_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewExplosionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewExplosionList) ProtoMessage() {}

func (x *NewExplosionList) ProtoReflect() protoreflect.Message {
	mi := &file_idl_quic_world_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewExplosionList.ProtoReflect.Descriptor instead.
func (*NewExplosionList) Descriptor() ([]byte, []int) {
	return file_idl_quic_world_proto_rawDescGZIP(), []int{3}
}

func (x *NewExplosionList) GetExplosionBorn() []*NewExplosion {
	if x != nil {
		return x.ExplosionBorn
	}
	return nil
}

type Explosion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Explosion) Reset() {
	*x = Explosion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_quic_world_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Explosion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Explosion) ProtoMessage() {}

func (x *Explosion) ProtoReflect() protoreflect.Message {
	mi := &file_idl_quic_world_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Explosion.ProtoReflect.Descriptor instead.
func (*Explosion) Descriptor() ([]byte, []int) {
	return file_idl_quic_world_proto_rawDescGZIP(), []int{4}
}

func (x *Explosion) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Explosion) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type GetExplosionList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Explosion []*Explosion `protobuf:"bytes,1,rep,name=explosion,proto3" json:"explosion,omitempty"`
}

func (x *GetExplosionList) Reset() {
	*x = GetExplosionList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_quic_world_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExplosionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExplosionList) ProtoMessage() {}

func (x *GetExplosionList) ProtoReflect() protoreflect.Message {
	mi := &file_idl_quic_world_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExplosionList.ProtoReflect.Descriptor instead.
func (*GetExplosionList) Descriptor() ([]byte, []int) {
	return file_idl_quic_world_proto_rawDescGZIP(), []int{5}
}

func (x *GetExplosionList) GetExplosion() []*Explosion {
	if x != nil {
		return x.Explosion
	}
	return nil
}

var File_idl_quic_world_proto protoreflect.FileDescriptor

var file_idl_quic_world_proto_rawDesc = []byte{
	0x0a, 0x14, 0x69, 0x64, 0x6c, 0x2f, 0x71, 0x75, 0x69, 0x63, 0x2f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x50, 0x0a, 0x04,
	0x52, 0x6f, 0x63, 0x6b, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x2d,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x04, 0x72, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x52, 0x6f, 0x63, 0x6b, 0x52, 0x04, 0x72, 0x6f, 0x63, 0x6b, 0x22, 0x2a, 0x0a,
	0x0c, 0x4e, 0x65, 0x77, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x4c, 0x0a, 0x10, 0x4e, 0x65, 0x77,
	0x45, 0x78, 0x70, 0x6c, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x38, 0x0a,
	0x0d, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x6f, 0x72, 0x6e, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4e, 0x65, 0x77, 0x45,
	0x78, 0x70, 0x6c, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x73,
	0x69, 0x6f, 0x6e, 0x42, 0x6f, 0x72, 0x6e, 0x22, 0x27, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x6c, 0x6f,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79,
	0x22, 0x41, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x6c, 0x6f, 0x73, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x65,
	0x78, 0x70, 0x6c, 0x6f, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x65, 0x78, 0x70, 0x6c, 0x6f, 0x73,
	0x69, 0x6f, 0x6e, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x71, 0x75, 0x69, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_quic_world_proto_rawDescOnce sync.Once
	file_idl_quic_world_proto_rawDescData = file_idl_quic_world_proto_rawDesc
)

func file_idl_quic_world_proto_rawDescGZIP() []byte {
	file_idl_quic_world_proto_rawDescOnce.Do(func() {
		file_idl_quic_world_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_quic_world_proto_rawDescData)
	})
	return file_idl_quic_world_proto_rawDescData
}

var file_idl_quic_world_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_idl_quic_world_proto_goTypes = []interface{}{
	(*Rock)(nil),             // 0: game.Rock
	(*GetRockList)(nil),      // 1: game.GetRockList
	(*NewExplosion)(nil),     // 2: game.NewExplosion
	(*NewExplosionList)(nil), // 3: game.NewExplosionList
	(*Explosion)(nil),        // 4: game.explosion
	(*GetExplosionList)(nil), // 5: game.GetExplosionList
}
var file_idl_quic_world_proto_depIdxs = []int32{
	0, // 0: game.GetRockList.rock:type_name -> game.Rock
	2, // 1: game.NewExplosionList.explosionBorn:type_name -> game.NewExplosion
	4, // 2: game.GetExplosionList.explosion:type_name -> game.explosion
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_idl_quic_world_proto_init() }
func file_idl_quic_world_proto_init() {
	if File_idl_quic_world_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_quic_world_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_quic_world_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRockList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_quic_world_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewExplosion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_quic_world_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewExplosionList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_quic_world_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Explosion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_quic_world_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExplosionList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_quic_world_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idl_quic_world_proto_goTypes,
		DependencyIndexes: file_idl_quic_world_proto_depIdxs,
		MessageInfos:      file_idl_quic_world_proto_msgTypes,
	}.Build()
	File_idl_quic_world_proto = out.File
	file_idl_quic_world_proto_rawDesc = nil
	file_idl_quic_world_proto_goTypes = nil
	file_idl_quic_world_proto_depIdxs = nil
}
