// Code generated by hertz generator.

package room

import (
	"github.com/cloudwego/hertz/pkg/app"
	"tank_war/server/cmd/api/biz/router/common"
	"tank_war/server/shared/consts"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getroomlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roomMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createroomMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		common.PasetoAuth(consts.User),
	}
}

func _joinroomMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		common.PasetoAuth(consts.User),
	}
}
